version: '3.3'
services:
  php:
    container_name: pract_site
    build: docker/php-fpm
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/pract:cached

  nginx:
    container_name: pract_nginx
    restart: always
    build: docker/nginx
    ports:
      - '80:80'
    links:
      - php
    volumes:
      - ./:/var/www/pract:cached
      - ./docker/var/logs/nginx/:/var/log/pract:cached
